In [77]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn .linear_model  import Perceptron
from sklearn.metrics import accuracy_score, classification_report,  confusion_matrix
from tensorflow.keras.models import  Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.layers import Conv2D
from tensorflow.keras.layers import  Flatten
from tensorflow.keras.layers import MaxPooling2D

In [65]:
df=pd.read_csv("mnist.csv")

In [66]:
df.shape

(42000, 785)

In [67]:
# Check for missing values and general dataset info
print("Missing values summary:", df.isnull().sum().sum())
display(df.head())

Missing values summary: 0

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [68]:
# 1. Handle missing values by dropping rows with NaN
df_cleaned = df.dropna().copy()

In [69]:
df_cleaned.dtypes

label       int64
pixel0      int64
pixel1      int64
pixel2      int64
pixel3      int64
            ...
pixel779    int64
pixel780    int64
pixel781    int64
pixel782    int64
pixel783    int64
Length: 785, dtype: object

In [70]:
# Separate the dataset into features (X) and target labels (y)
y = df_cleaned['label'].astype(int)
X = df_cleaned.drop(columns=['label'])

print("Features (X) shape:", X.shape)
print("Target labels (y) shape:", y.shape)

Features (X) shape: (42000, 784)
Target labels (y) shape: (42000,)

In [71]:
#Train test Data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [72]:
# X_train ,  X_test data  convert them  into  range between  (1-0)
X_train  = X_train.astype('float32')/255
X_test = X_test.astype('float32')/255

In [78]:
# X_train,  X_test  date reshape to image  pixels  and  array
X_train_img = X_train.values.reshape(-1,28,28)
X_test_img = X_test.values.reshape(-1,28,28)

In [73]:
y_train_cat= to_categorical(y_train,10)
y_test_cat= to_categorical(y_test,10)

In [83]:
Perceptron= Sequential([
    Flatten(input_shape=(28, 28)),
    Dense(10, activation="softmax")
])

In [84]:
Perceptron.compile(optimizer="sgd",
                   loss="categorical_crossentropy",
                   metrics=["accuracy"])

In [85]:
history_percp=Perceptron.fit(X_train_img,
                             y_train_cat,
                             epochs=5,
                             batch_size=32,
                             validation_data=(X_test_img, y_test_cat),
                             verbose=1)

Epoch 1/5
1050/1050 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.7717 - loss: 0.9590 - val_accuracy: 0.8569 - val_loss: 0.6058
Epoch 2/5
1050/1050 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8683 - loss: 0.5306 - val_accuracy: 0.8755 - val_loss: 0.4863
Epoch 3/5
1050/1050 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8820 - loss: 0.4539 - val_accuracy: 0.8817 - val_loss: 0.4384
Epoch 4/5
1050/1050 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8890 - loss: 0.4164 - val_accuracy: 0.8877 - val_loss: 0.4116
Epoch 5/5
1050/1050 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.8944 - loss: 0.3930 - val_accuracy: 0.8914 - val_loss: 0.3934

In [86]:
acc_perp=Perceptron.evaluate(X_test_img, y_test_cat,verbose=0)[1]

In [87]:
acc_perp

0.8914285898208618